server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/

spring:
  application:
    name: service-ribbon

turbine:
  app-config: service-ribbon
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream