# spring boot admin 注册服务
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8090
server:
  port: 8558
# 服务暴露时间
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS