# spring boot admin 注册服务
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8090 # spring boot admin server 服务地址
server:
  port: 8558

management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露的接口服务
  endpoint:
    health:
      show-details: ALWAYS