server:
  port: 8080
management:
  endpoint:
    web:
      exposure:
        include: '*'
        exclude: env
    health: #开启health查询全部的信息展示
      show-details: always
spring:
  redis:
    sentinel:
      nodes:

