server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env
    health: #开启health查询全部的信息展示
      show-details: always



spring:
  security:
    user:
      name: zhoucg
      password: zhoucg