spring:
  application:
    name: zipkin-service
  zipkin:
    base-url: http://localhost:9411



server:
  port: 8990


eureka:
  client:
    serviceUrl:
      defaultZone:  http://zhoucg:zhoucg@localhost:8761/eureka/
