# nacos服务集群地址信息

# 服务端口
server:
  port: 18087


spring:
  application:
    name: dubbo-provider
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    base-packages: com.spring.nacos.dubbo.server
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://192.168.129.128:2181
    # 挂载到nacos
    #address: nacos://127.0.0.1:8848
    # 挂载到spring-cloud 注册中心
    #address: spring-cloud://localhost
  application:
    name: dubbo-provider
