eureka:
  client:
    serviceUrl:
      # eureka service 使用了security
      defaultZone:  http://zhoucg:zhoucg@localhost:8761/eureka/

# 配置对应的服务端口
server:
  port: 8999


# spring cloud gateway 介绍：https://spring.io/projects/spring-cloud-gateway

# router:路由是网关的基本构建，它由ID,目标URL，谓词集合和过滤器集合定义，如果聚合谓词为真，则匹配路由。

#Predicate 断言：这是一个Java 8 Function Predicate。输入类型是 Spring Framework ServerWebExchange。
#  这允许开发人员可以匹配来自HTTP请求的任何内容，例如Header或参数。

# 网关配置

#  StripPrefix 通过配置parts来表示截取路径前缀的数量， 如这个例子，如果请求的接口为 http://localhost:8999/service/provider?name=zhoucgwl
#  则路径会变成 /provider?name=zhoucgwl 会将/service 截取掉
spring:
  # spring-boot-starter-zipkin 客户端配置，连接到对应的zipkin服务url配置
  zipkin:
    base-url: http://localhost:9411
  # 采样率 https://segmentfault.com/a/1190000019037588 固定比率
  # 使用spring.sleuth.sampler.probability进行配置时，实际上是使用的是：ProbabilityBasedSampler 进行过滤判断，：表示一定概率（采样率）进行过滤掉对应的结果（BitSet底层）
  # 使用spring.sleuth.sampler.probability进行配置时，实际上是使用的是：RateLimitingSampler：表示每秒间隔接收trace的量，最小为o，最大为integer的最大值
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          # 使用服务发现路由
          enabled: true
      # see  GatewayProperties# routes 每一个routes 配置含有id, url, order, filters, predicates组成
      # id配置： 默认配置：UUID.randomUUID().toString(); 可以不配置
      # uri配置：标准的URI配置结果 lb
      # predicates配置： 两种配置方式：name args text see:https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.2.3.RELEASE/reference/html/#configuring-route-predicate-factories-and-gateway-filter-factories
      #                 系统默认的Predicates: Path,Between,Before,Query,Cookie,Header,Host,Method,ReadBody,Weight,CloudFoundry
      # filters:
      routes:
        # 配置对应的 service-hi
        - id: spring-provider-A
          uri: lb://spring-provider-A
          predicates:
             - Path=/service/**
             - After=2018-12-25T14:33:47.789+08:00
             - Header=hello,A #注意对应的Header的配置信息，当前表示url需要传递一个header参数，hello=A
          filters:
            - StripPrefix=1
        - id: spring-eureka-client
          uri: lb://spring-eureka-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
        - id: spring-consumer-feign
          uri: lb://spring-consumer-feign
          predicates:
            - Path=/feign/**
          filters:
            - StripPrefix=1
      enabled: true # 默认的网关配置，如果引用了spring-cloud-starter-gateway ，又不想用它，设置为false
  application:
    name: spring-gateway


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS