spring:
  application:
    name: service-feign

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/



#开启feign hystix熔断器
feign:
  hystrix:
    enabled: true
  #httpclient:
  #  enabled: true



